default: &default
  adapter: postgresql
  encoding: unicode
  user: manoel
  password: manoel
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_api_development
  user: manoel
  password: manoel

test:
  <<: *default
  database: ecommerce_api_test
  user: manoel
  password: manoel

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV["ECOMMERCE_API_DATABASE_PASSWORD"] %>
